DROP TABLE IF EXISTS directors_films;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS users_likes_films;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS user_friends;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS rating_mpa;
DROP TABLE IF EXISTS directors;

CREATE TABLE film_genres
(
    film_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL
);
CREATE TABLE films
(
    id BIGINT generated BY DEFAULT AS IDENTITY,
    description VARCHAR(200),
    duration INTEGER,
    name VARCHAR(255) NOT NULL,
    rate INTEGER,
    release_date DATE,
    rating_mpa_id BIGINT,
    PRIMARY KEY (id)
);
CREATE TABLE genres
(
    id BIGINT generated BY DEFAULT AS IDENTITY,
    title VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE TABLE user_friends
(
    id BIGINT generated BY DEFAULT AS IDENTITY,
    approved BOOLEAN NOT NULL,
    friend_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE users
(
    id BIGINT generated BY DEFAULT AS IDENTITY,
    birthday DATE,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE TABLE users_likes_films
(
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL
);
CREATE TABLE rating_mpa
(
    id BIGINT auto_increment,
    title VARCHAR(5) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE directors
(
    id BIGINT generated BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE directors_films
(
    director_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL
);

ALTER TABLE film_genres ADD CONSTRAINT uk_film_id_genre_id UNIQUE (film_id, genre_id);
ALTER TABLE genres ADD CONSTRAINT uk_genre_title UNIQUE (title);
ALTER TABLE user_friends ADD CONSTRAINT uk_user_friend UNIQUE (user_id, friend_id);
ALTER TABLE users ADD CONSTRAINT uk_user_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT uk_user_login UNIQUE (login);
ALTER TABLE user_friends ADD CONSTRAINT fk_friend_id FOREIGN KEY (friend_id) REFERENCES users;
ALTER TABLE user_friends ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE users_likes_films ADD CONSTRAINT fk_film_like_id FOREIGN KEY (film_id) REFERENCES films;
ALTER TABLE users_likes_films ADD CONSTRAINT fk_user_like_id FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE films ADD CONSTRAINT fk_rating_mpa_films FOREIGN KEY (rating_mpa_id) REFERENCES rating_mpa;
ALTER TABLE directors_films ADD CONSTRAINT fk_director_id FOREIGN KEY (director_id) REFERENCES directors;
ALTER TABLE directors_films ADD CONSTRAINT fk_film_id FOREIGN KEY (film_id) REFERENCES films;

INSERT INTO rating_mpa (title) VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');
INSERT INTO genres (title) VALUES ('Комедия'), ('Драма'), ('Мультфильм'), ('Триллер'), ('Документальный'), ('Боевик');

INSERT INTO users (email, login, name) VALUES ('test1@mail.ru', 'test_1', 'test_1'),
                                              ('test2@mail.ru', 'test_2', 'test_2'),
                                              ('test3@mail.ru', 'test_3', 'test_3')